#!/bin/sh

ARDUINO_LIBRARIES_PATH=~/Arduino/libraries
PWD=$(pwd)
CLEAR_FLAG=-c

FLEX=FlexLibrary
WEIGHT=WeightSensorLib
DISPLAY=SerialDisplayLib
FILTER=Filter
SOUND=SoundSensorLib
AMBIENT=AmbientSensorLib
LIGHT=LightSensorLib
LED=LEDLib
SWITCH=SwitchLib

if [ "$1" = $CLEAR_FLAG ]; then
  echo " --- OLD FILES CLEARED --- "
  rm $ARDUINO_LIBRARIES_PATH/$FLEX
  rm $ARDUINO_LIBRARIES_PATH/$WEIGHT
  rm $ARDUINO_LIBRARIES_PATH/$DISPLAY
  rm $ARDUINO_LIBRARIES_PATH/$FILTER
  rm $ARDUINO_LIBRARIES_PATH/$SOUND
  rm $ARDUINO_LIBRARIES_PATH/$AMBIENT
  rm $ARDUINO_LIBRARIES_PATH/$LIGHT
  rm $ARDUINO_LIBRARIES_PATH/$LED
  rm $ARDUINO_LIBRARIES_PATH/$SWITCH
fi

ln -s $PWD/FlexSensor/$FLEX $ARDUINO_LIBRARIES_PATH
ln -s $PWD/WeightSensor/$WEIGHT $ARDUINO_LIBRARIES_PATH
ln -s $PWD/SerialDisplay/$DISPLAY $ARDUINO_LIBRARIES_PATH
ln -s $PWD/$FILTER $ARDUINO_LIBRARIES_PATH
ln -s $PWD/SoundSensor/$SOUND $ARDUINO_LIBRARIES_PATH
ln -s $PWD/AmbientSensor/$AMBIENT $ARDUINO_LIBRARIES_PATH
ln -s $PWD/LightSensor/$LIGHT $ARDUINO_LIBRARIES_PATH
ln -s $PWD/LED/$LED $ARDUINO_LIBRARIES_PATH
ln -s $PWD/Switch/$SWITCH $ARDUINO_LIBRARIES_PATH

echo $ARDUINO_LIBRARIES_PATH
ls -la $ARDUINO_LIBRARIES_PATH